menu:
- {name: 'publications', url: '/publications'}
- {name: 'cv', url: '/cv'}

social:
- {icon: 'scholar', link: 'https://scholar.google.com/citations?user=KfOM898AAAAJ&hl=en&oi=ao'}
- {icon: 'twitter', link: 'https://x.com/_coltoncasto'}
- {icon: 'github', link: 'https://github.com/coltoncasto'}
